version: '3'

networks:
  djangonet:

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - djangonet

  edutrack:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: docker.io/library/edutrack
    container_name: edutrack_container
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - djangonet
    depends_on:
      - redis
    environment:
      - TZ=Asia/Kolkata