# Generated by Django 4.2.1 on 2023-05-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directoremail', models.CharField(max_length=50)),
                ('semester1_deletion_date', models.DateField(blank=True, null=True)),
                ('semester1_deletion_time', models.TimeField(blank=True, null=True)),
                ('semester2_deletion_date', models.DateField(blank=True, null=True)),
                ('semester2_deletion_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=200)),
                ('opt_2', models.CharField(max_length=200)),
                ('opt_3', models.CharField(max_length=200)),
                ('opt_4', models.CharField(max_length=200)),
                ('right_opt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNum', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(default='female', max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(default=None, max_length=20)),
                ('testName', models.CharField(max_length=20)),
                ('numberOfQuestions', models.IntegerField(default=None)),
                ('DateOfExam', models.DateField(default=None)),
                ('StartTime', models.TimeField(default=None)),
                ('EndTime', models.TimeField(default=None)),
                ('branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=20)),
                ('profemail', models.CharField(max_length=50)),
                ('subjectName', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(default=0)),
                ('wrongAns', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('TimeRemaining', models.IntegerField()),
                ('startTime', models.TimeField(default=None)),
                ('endTime', models.TimeField(default=None)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testdetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedAnswer', models.CharField(max_length=100)),
                ('attempt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studentscores')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testdetails'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(default=None, max_length=20)),
                ('questionBank', models.FileField(default=None, null=True, upload_to='QuestionBanks/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='HODs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college')),
            ],
        ),
        migrations.CreateModel(
            name='BranchToHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodemail', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college'),
        ),
    ]
