# Generated by Django 4.2.1 on 2023-05-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='semester1_deletion_date',
            new_name='semester1_End_date',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='semester2_deletion_date',
            new_name='semester2_End_date',
        ),
        migrations.RemoveField(
            model_name='college',
            name='semester1_deletion_time',
        ),
        migrations.RemoveField(
            model_name='college',
            name='semester2_deletion_time',
        ),
    ]
