# Generated by Django 4.1.7 on 2023-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_professors_college_professors_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('subjectID', models.CharField(max_length=20)),
                ('profemail', models.CharField(max_length=50)),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='professors',
            name='subjectID',
        ),
        migrations.RemoveField(
            model_name='testdetails',
            name='subject',
        ),
        migrations.AddField(
            model_name='testdetails',
            name='subjectID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='branch',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
